### ISSUE TITLE
Strange behavior in git directories 

### ISSUE THREAD

**Issue by py4object** [oh-my-fish/theme-fishbone#4]
![screenshots](https://cloud.githubusercontent.com/assets/5759804/18002539/1d4fce9e-6b91-11e6-8ba3-3022b9f2bcdf.png)

**Comment by bobthecow** [comment]
Is this a git directory which is initialized but has no commits yet?

**Comment by pantuza** [comment]
Looking closer to the issue with @dnsaoki2 and @raelmax, we just realize that the problem was exactly what @bobthecow said. If directory is a repository with no commits, our prompt shows the error.

Before, we was using `git rev-parse --abbrev-ref HEAD` to show current branch. If there is no commits, git throws this error. 

Fish has a variable called _git_branch_name_ that is quite more simple and compatible. 

For now @py4object, if you run `omf update` you will get it working as expected.

Thank you for reporting the issue : )

**Comment by py4object** [comment]
Hi thanks for the great work ,the issue was  solved  when i updated it

**Comment by pantuza** [comment]
🍺  🍔
