### ISSUE TITLE
Uptime apperance bug

### ISSUE THREAD

**Issue by akaia-shadowfox** [oh-my-fish/theme-fishbone#6]
Buggy appearance, when uptime == day
![image](https://user-images.githubusercontent.com/8805308/42350895-293e7f02-80bb-11e8-8e6e-2d5a882370a7.png)

**Comment by pantuza** [comment]
Hi @katecanaveral,

well noted! Thank you for the report. We will fix it as soon as possible.

**Comment by pantuza** [comment]
Hi, @katecanaveral.

I've missed [this line](https://github.com/coreutils/coreutils/blob/master/src/uptime.c#L150) of uptime code from coreutils. I think the problem is now solved. I've tested it on my machine. If the problem continue, please let me know.

To update **fishbone** you should run:

```fish
$> omf update  # It will automatically update all plugins and themes 
```
Then just try to login again by running, for example:
```fish
$> su {your_user_name}
```

Cheers.

**Comment by akaia-shadowfox** [comment]
Thanks, good job!
